from .pulemet import Pulemet, as_completed_return_exception
